apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSRunAsNonRoot
metadata:
  name: require-runasnonroot-audit-zone
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaces: ["audit-zone"]
